#include "ti/devices/msp/m0p/mspm0g350x.h"
#include "../inc/DAC.h"
#include <stdint.h>
#include "Textures.h"
#include "../inc/ST7735.h"

static const uint16_t circuitBoardTexture[TEX_WIDTH * TEX_HEIGHT] = {
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, TRACE_COLOR, TRACE_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, TRACE_COLOR, TRACE_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    COMPONENT_COLOR, COMPONENT_COLOR, COMPONENT_COLOR, COMPONENT_COLOR, COMPONENT_COLOR, COMPONENT_COLOR, COMPONENT_COLOR, COMPONENT_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, TRACE_COLOR, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
    CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN, CIRCUIT_BOARD_GREEN,
};

void Textures_Init() {
    for(int texNum = 0; texNum < 8; texNum++) {
        for(int x = 0; x < TEX_WIDTH; x++) {
            for(int y = 0; y < TEX_HEIGHT; y++) {
                uint16_t color = 0; // Initialize color
                uint8_t red = 0, green = 0, blue = 0; // Initialize color components

                if (texNum == 0) {
                    // Flat red texture with black cross
                    red = 31 * (x != y && x != TEX_WIDTH - y - 1); // Scale down red to 0-31
                    green = 0;
                    blue = 0;
                } else if (texNum == 1) {
                    int xycolor = (y * 128 / TEX_HEIGHT) + (x * 128 / TEX_WIDTH);
                    red = xycolor * 31 / 255;   // Scale to 0-31
                    green = xycolor * 63 / 255;  // Scale to 0-63
                    blue = xycolor * 31 / 255;  // Scale to 0-31
                } else if (texNum == 2) {
                    int xycolor = (y * 128 / TEX_HEIGHT) + (x * 128 / TEX_WIDTH);
                    red = xycolor * 31 / 255;   // Scale to 0-31
                    green = xycolor * 63 / 255;  // Scale to 0-63
                    blue = 0;
                } else if (texNum == 3) {
                    int xorcolor = (x * 256 / TEX_WIDTH) ^ (y * 256 / TEX_HEIGHT);
                    red = xorcolor * 31 / 255;   // Scale to 0-31
                    green = xorcolor * 63 / 255;  // Scale to 0-63
                    blue = xorcolor * 31 / 255;  // Scale to 0-31
                } else if (texNum == 4) {
                    int xorcolor = (x * 256 / TEX_WIDTH) ^ (y * 256 / TEX_HEIGHT);
                    red = 0;
                    green = xorcolor * 63 / 255;  // Scale to 0-63
                    blue = 0;
                } else if (texNum == 5) {
                    red = 31 * (x % 16 && y % 16); // Scale down red to 0-31
                    green = 0;
                    blue = 0;
                } else if (texNum == 6) {
                    // Circuit board pattern (hardcoded)
                    textures[texNum][y * TEX_WIDTH + x] = circuitBoardTexture[y * TEX_WIDTH + x];
                    continue; // Skip the rest of the inner loop for this texture
                } else if (texNum == 7) {
                    // All Black
                    color = 0xFFFF;
                    textures[texNum][y * TEX_WIDTH + x] = color;
                    continue; // Skip color conversion
                }

                // Convert to RGB565 directly
                color = ((red & 0x1F) << 11) | ((green & 0x3F) << 5) | ((blue & 0x1F));
                textures[texNum][y * TEX_WIDTH + x] = color;
            }
        }
    }
}